" ======================================================================
" Title: Cantoraz's vimrc
" Author: Cantoraz
" License: GPLv3
" Date: Fri, 2012-02-10 19:30:16 CST

" ======================================================================
" # Dependencies - Libraries/Applications outside of vim
" ======================================================================
" Pep8
" Ack
" Rake & Ruby for command-t
" nose, django-nose

" ======================================================================
" # Plugins Management
" ======================================================================
	" ======================================================================
	" ## Vundle - Manage our vim plugins
	" ======================================================================
	" Load all plugins
	set nocompatible			" be iMproved
	filetype off				" required!
	set rtp+=~/.vim/bundle/vundle/
	call vundle#rc()

	" let Vundle manage Vundel
	Bundle 'gmarik/vundle'
								" Manage our vim plugins 
	"
	" My Bundles here:
	"
	" original repos on github
	" Eg, Bundle 'lokaltog/vim-easymotion'
	" Eg, Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
	"
	" vim-scripts repos
	" Eg, Bundle 'L9'
	" Eg, Bundle 'FuzzyFinder'
	" Eg, Bundle 'rails.vim'
	"
	" non github repos
	" Eg, Bundle 'git://git.wincent.com/command-t.git'

	"Bundle 'vim-scripts/ack.vim'
	Bundle 'mileszs/ack.vim'
								" Plugin for the Perl module / CLI script 'ack'
	Bundle 'wincent/Command-T'
								" Allows easy search and opening of files within a given path 
	"Bundle 'Raimondi/delimitMate'
    Bundle 'delimitMate.vim'
								" Provides insert mode auto-completion for quotes, parens, brackets, etc.
	Bundle 'tpope/vim-fugitive'
								" Interface with git from vim
	Bundle 'tpope/vim-git'
								" Syntax highlighting for git config files
	Bundle 'sjl/gundo.vim'
								" Visual Undo in vim with diff's to check the differences
	Bundle 'vim-scripts/indentpython.vim'
								" An alternative indentation script for python
	Bundle 'vim-scripts/matchit.zip'
								" Extended % matching for HTML, LaTeX, and many other languages
	"Bundle 'reinh/vim-makegreen'
								" Generic test runner that works with nose
	"Bundle 'vim-scripts/minibufexpl.vim'
	"Bundle 'fholgado/minibufexpl.vim'
	"Bundle 'sontek/minibufexpl.vim'
								" Visually display what buffers are currently opened
	Bundle 'vim-scripts/The-NERD-tree'
								" A tree explorer plugin for navigating the filesystem
	Bundle 'tpope/vim-pathogen'
								" Better Management of VIM plugins 
	"Bundle 'vim-scripts/pep8'
								" Check your python source files with PEP8
	"Bundle 'vim-scripts/Pydiction'
								" Tab-complete your Python code
	"Bundle 'fs111/pydoc.vim'
								" pydoc integration for the best text editor on earth
	Bundle 'mitechie/pyflakes-pathogen'
								" Underlines and displays errors with Python on-the-fly
								" an improved pyflakes module is INCLUDED with this plugin,
								" so you don't need to install it separately
	"Bundle 'alfredodeza/pytest.vim'
								" Run py.test test's from within vim 
	Bundle 'vim-scripts/python.vim'
								" Bundle 'vim-scripts/python.vim--Vasiliev'
	Bundle 'tpope/vim-rails'
								" Ruby on Rails power tools
	"Bundle 'klen/rope-vim'
	"Bundle 'sontek/rope-vim'
								" Pathogen compatable ropevim plugin.
								" Dont need install rope libs in system.
	Bundle 'vim-ruby/vim-ruby'
								" Vim/Ruby Configuration Files
	Bundle 'tpope/vim-rvm'
								" switch Ruby versions from inside Vim
	Bundle 'msanders/snipmate.vim'
								" Configurable snippets to avoid re-typing common comands
	Bundle 'altercation/vim-colors-solarized'
								" Precision colors for machines and people
	"Bundle 'ervandew/supertab'
								" Perform all your vim insert mode completions with Tab
	Bundle 'tpope/vim-surround'
								" Allows you to surround text with open/close tags
	Bundle 'vim-scripts/taglist.vim'
								" Source code browser (supports C/C++, java, perl, python, tcl, sql, php, etc)
	Bundle 'vim-scripts/TaskList.vim'
								" Eclipse like task list 
	Bundle 'Zenburn'
								" A low-contrast color scheme for Vim. 
	Bundle 'mattn/zencoding-vim'
								" Vim plugins for HTML and CSS hi-speed coding.

	" ======================================================================
	" ## Pathogen - organize our vim plugins out of Vundle
	" ======================================================================
	" Load pathogen with docs for all plugins
	call pathogen#runtime_append_all_bundles('nobundle')
	call pathogen#helptags()

" ======================================================================
" # General Settings
" ======================================================================
filetype plugin indent on   " required!
                            " trye to detect filetypes
                            " enable loading indent file for filetype
set helplang=cn             " Enable help in Chinese language

	" ======================================================================
	" ## File Reading/Writing
	" ======================================================================
	"set modeline                " Allow vim options to be embedded in files;
	"set modellines=5            " they must be within the first or last 5 lines.
	set noautowrite             " Never write a file unless I request it.
	set noautowriteall          " NEVER.
	set noautoread              " Don't automatically re-read changed files.
	set ffs=unix,mac,dos        " Try recognizing dos, unix and mac line endings.
	let &termencoding=&encoding " Encoding detection
	set fileencodings=ucs-bom,utf-8,cp936,euc-cn,cp950,big5,euc-tw,default,latin1

	" ======================================================================
	" ## Display
	" ======================================================================
	syntax enable               " syntax highlighting
	set number                  " Display line numbers
	set numberwidth=1           " using only 1 column (and 1 space) while possible
	"set background=dark        " We are using dark background in vim
	set cursorline              " have a line indicate the cursor location
	"set nowrap                  " don't wrap text
	set linebreak               " don't wrap textin the middle of a world
	"set listchars=tab:>-,eol:$,trail:-,precedes:<,extends:>
	set listchars=tab:▸\ ,eol:↵

	set t_Co=256
	colorscheme zenburn

	if has('gui_running')
		set guicursor+=a:blinkon0
		set list                " displays tabs with :set list 
								" displays when a line runs off-screen
		if has("gui_macvim")    " MacVim
			let s:caz_guifont = "Menlo:h14"
			let s:caz_lines = 999
			let s:caz_columns = 84
		elseif has("gui_gtk2")  " GTK+2
			let s:caz_guifont = "DejaVu\ Sans\ Mono\ 12"
			let s:caz_lines = 50
			let s:caz_columns = 84
		elseif has("gui_win32") " WIN32
			let s:caz_guifont = "DejaVu\ Sans\ Mono:h13"
			let s:caz_lines = 38
			let s:caz_columns = 84
		endif

		let &guifont = s:caz_guifont
		let &lines = s:caz_lines
		if !exists('b:caz_columns_saved')
			let &columns = s:caz_columns
			let b:caz_columns_saved = &columns
		endif
	endif

	if exists("&colorcolumn")
		setlocal colorcolumn=80
		" Incompatible with MiniBufExpl, hack this color in used ColorScheme
		"hi ColorColumn term=reverse ctermbg=3 guibg=#3d3535
	endif

	" ====================================================================
	" ## Messages/Info/Status
	" ====================================================================
	"set vb t_vb=                " Disable all bells. I hate ringing/flashing.
	set title                   " show title in console title bar
	set ruler                   " show the cursor position all the time
	set shortmess+=a            " Use [+]/[RO]/[w] for modified/readonly/written.
	set laststatus=2            " Always show status line, even if only 1 window.
	" 缓冲区号 文件名 行数 修改 帮助 只读 编码 换行符 BOM ======== 字符编码 位置 百分比位置
	set statusline=%n\ %<%f\ %LL\ %{&modified?'[+]':&modifiable\|\|&ft=~'^\\vhelp\|qf$'?'':'[-]'}%h%r%{&fenc=='utf-8'\|\|&fenc==''?'':'['.&fenc.']'}%{&ff=='unix'?'':'['.&ff.']'}%{&bomb?'[BOM]':''}%{&eol?'':'[noeol]'}%=%{rvm#statusline()}%{fugitive#statusline()}\ 0x%-4.4B\ \ \ \ %-14.(%l,%c%V%)\ %P
	"set statusline=%<%f\ (%{&ft})%=%-19(%3l,%02c0%03V%)%{fugitive#statusline()}
	set wildmenu                " Menu completion in commond mode on <Tab>
	set wildmode=full           " <Tab> cycles between all matching choices.
	set wildignore+=*.o,*.obj,*.git,*.pyc
								" Ignore these files when completing
	set showcmd                 " Show incomplete normal mode commands as I type.
	set confirm                 " Y-N-C prompt if closing with unsaved changes.
	set report=0                " : commands always print changed line count.

	" ======================================================================
	" ## Moving/Editing
	" ====================================================================
	set backspace=2             " Allow backspacing over autoindext, EOL and BOL
	set nostartofline           " Avoid moving cursor to BOL when jumping around
	set scrolloff=3             " Keep 3 context lines above and below the cursor
	set virtualedit=block       " Let cursor move past the last char in <C-v> mode

	set showmatch               " Briefly jump to a paren once it's balanced
	set matchtime=2             " (for only .2 seconds)
	set matchpairs+=<:>         " show matching <> (xml/html mainly) as well

	set foldmethod=indent       " allow us to fold on indents
	set foldlevel=99            " don't fold by default

	"au BufEnter * lcd %:p:h	" Auto change the directory to the current file I'm working on

	"autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
	"autocmd InsertLeave * if pumvisible() == 0|pclose|endif
								" close preview window automatically when we move around

	" ======================================================================
	" ## Indentation
	" ======================================================================
	set autoindent              " always set autoindenting on
	set tabstop=4               " <tab> inserts 4 spaces
	set shiftwidth=4            " and an indent level is 4 spaces wide
	set softtabstop=4           " <BS> over an autoindent deletes both spaces.
	"set expandtab               " Use spaces, not tabs, for autoindent/tab key.
	"set shiftround              " rounds indent to a multiple of shiftwidth

	" ======================================================================
	" ## Completion
	" ======================================================================
	set completeopt=menuone,longest,preview
								" don't select first item, follow typeing in autocomplete
	set pumheight=20            " Keep a small completion window

	" ======================================================================
	" ## Searching/Patterns
	" ======================================================================
	set ignorecase              " Default to using case insensitive searches,
	set smartcase               " unless uppercase letters are used in the regex.
	set hlsearch                " Highlight searches by default.
	set incsearch               " Incrementally search while typing a /regex
	"set grepprg=ack-prep        " replace the default grep program with ack

	" ======================================================================
	" ## Key Mapping
	" ======================================================================
	set macmeta					" Enable option key as meta key under Mac
	"let mapleader=","			" Change the leader to be a comma vs splash

	" brings up my .vimrc
	map <silent> <leader>v :e ~/.vimrc<CR>
	" reloads .vimrc -- making all changes active (have to save first)
	map <silent> <leader>V :source ~/.vimrc<CR>:exe ":echo 'vimrc reloaded'"<CR>

	" List/Cycle buffers
	map <C-X><C-B> :ls<CR>
	map <C-N> :bnext<CR>
	map <C-P> :bprevious<CR>

	" Cycle windows
	map <C-J> <C-W>j
	map <C-K> <C-W>k
	map <C-L> <C-W>l
	map <C-H> <C-W>h

	" Ctrl-c to jank/copy, Ctrl-v to paste
	map <C-C> "+y
	map <C-V> "+p

	" Autocomplete
	imap <F2> <C-X><C-O>

	" New line above
	imap <S-CR> <Esc>O

	" Insert current timestamp/date/time
	if exists('*strftime')
		imap <silent> <C-X><C-D><C-F> <C-R>=strftime('%a, %F %T %Z')<CR>
		imap <silent> <C-X><C-D><C-T> <C-R>=strftime('%T %Z')<CR>
		imap <silent> <C-X><C-D><C-D> <C-R>=strftime('%F')<CR>
	endif

	" Folding
	nnoremap <Space> za

	" Change working directory
	nnoremap <leader>. :silent lcd %:p:h<CR>:echo expand('%:p:h')<CR>

	" Toggle line numbers and fold column for easy copying
	nnoremap <leader>tn :set nonumber!<CR>:set foldcolumn=0<CR>

	" Turn off hlsearch on enter
	nnoremap <CR> :nohlsearch<CR>

	" Seriously, guys. It's not like :W is bound to anything anyway.
	"command! W :w

	" open/close the quickfix window
	nmap <leader>c :copen<CR>
	nmap <leader>C :cclose<CR>

	" for when we forget to use sudo to open/edit a file
	"cmap w!! w !sudo tee % >/dev/null

	" and lets make these all work in insert mode too ( <C-O> makes next cmd
	" happend as if in command mode )
	"imap <C-W> <C-O><C-W>

" ======================================================================
" # FileType Setting
" ======================================================================
	" ======================================================================
	" ## C
	" ======================================================================
	au FileType c setlocal ts=4 sts=4 sw=4 sta et ai
	au FileType c set omnifunc=ccomplete#Complete

	" ======================================================================
	" ## CSS
	" ======================================================================
	au FileType css setlocal ts=2 sts=2 sw=2 noet ai
	au FileType css set omnifunc=csscomplete#CompleteCSS
	
	" ======================================================================
	" ## HTML
	" ======================================================================
	au FileType html,xhtml setlocal ts=2 sts=2 sw=2 noet ai
	au FileType html set omnifunc=htmlcomplete#CompleteTags

	" ======================================================================
	" ## Javscript
	" ======================================================================
	au FileType javascript setlocal ts=4 sts=4 sw=4 et ai
	au FileType javascript set omnifunc=javascriptcomplete#CompleteJS
	au FileType javascript set makeprg=jsl\ %

	" ======================================================================
	" ## Python
	" ======================================================================
	au FileType python setlocal ts=4 sts=4 sw=4 sta et ai
	au FileType python set omnifunc=pythoncomplete#Complete
	au FileType python set errorformat=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
	"au FileType python compiler nose

	" Improve formatting and display of improper indentation.
	" Refer: http://www.vim.org/scripts/script.php?script_id=790
	"au FileType python set complete+=k~/.vim/bundle/python.vim--Vasiliev/syntax/python3.0.vim isk+=.,(

	" Ability to run script beging edited.
	" Execute file being edited with <F11>
	au FileType python map <buffer> <F11> :w<CR>:!/usr/bin/env python %<CR>
	" Debug file begin edited with <Shift> + <F11>
	au FileType python map <buffer> <S-F11> :w<CR>:!/usr/bin/env python -m pdb %<CR>

	" Trim trailing whitespace
	"au BufWritePre *.py normal m`:%s/\s\+$//e``

	" turn off hlsearch and update pyflakes on enter
	"au FileType python nnoremap <CR> :nohlsearch\|:call PressedEnter()<CR>

		" ====================================================================
		" ### Plugins for Python
		" ====================================================================
			" ====================================================================
			" #### Pep8
			" ====================================================================
			"let g:pep8_map='<leader>8'  " Run pep8

			" ====================================================================
			" #### Py.test
			" ====================================================================
			" Execute the tests
			"nmap <silent><leader>tf <Esc>:Pytest file<CR>
			"nmap <silent><leader>tc <Esc>:Pytest class<CR>
			"nmap <silent><leader>tm <Esc>:Pytest method<CR>

			" Cycle through test errors
			"nmap <silent><leader>tn <Esc>:Pytest next<CR>
			"nmap <silent><leader>tp <Esc>:Pytest previous<CR>
			"nmap <silent><leader>te <Esc>:Pytest error<CR>

			" ====================================================================
			" #### Pydiction
			" ====================================================================
			"let g:pydiction_location = '$HOME/.vim/bundle/Pydiction/complete-dict'
			" The default menu height is 15.
			"let g:pydiction_menu_height = 20

			" ====================================================================
			" #### Pyflakes
			" ====================================================================
			" Don't let pyflakes use the quickfix window
			let g:pyflakes_use_quickfix=0

			" clear the search bufrer when hitting return and update pyflakes checks
			function! PressedEnter()
				:nohlsearch
				if &filetype == 'python'
					:PyflakesUpdate
				end
			endfunction

			" ====================================================================
			" #### Rope
			" ====================================================================
			" Jump to the definition of whatever the cursor is on 
			"map <leader>j :RopeGotoDefinition<CR>
			" Rename whatever the cursor is on (including references to it)
			"map <leader>r :RopeRename<CR>

			" ====================================================================
			" #### Nose, Django-Nose, MakeGreen
			" ====================================================================
			" Run django tests
			"map <leader>dt :set makeprg=pyton\ manger.py\ test\|:call MakeGreen()<CR>

	" ======================================================================
	" ## Ruby " ======================================================================
	au FileType ruby,eruby,yaml setlocal ts=2 sts=2 sw=2 sta et ai
	au BufRead,BufNewFile Gemfile,Rakefile,Thorfile,config.ru,Vagrantfile,Guardfile,Capfile set ft=ruby

	" ======================================================================
	" ## Plugins for Ruby
	" ======================================================================
		" ======================================================================
		" ### Vim-Ruby
		" ======================================================================
		autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
		autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
		autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1

" ======================================================================
" # General Plugins
" ======================================================================
	" ======================================================================
	" ## Ack searching
	" ======================================================================
	"nmap <leader>a <Esc>:Ack!

	" ======================================================================
	" ## Command-T
	" ======================================================================
	" Run command-t file search
	map <C-T><C-T> :CommandT<CR>
	map <C-T><C-B> :CommandTBuffer<CR>

	" ======================================================================
	" delimitMate"
	" ======================================================================
	let delimitMate_expand_cr = 1
	let delimitMate_expand_space = 1

	" ======================================================================
	" ## Gundo
	" ======================================================================
	" load the Gundo window
	map <leader>tu :GundoToggle<CR>

	" ======================================================================
	" ## MiniBufExpl
	" ======================================================================
	"let g:miniBufExplSplitToEdge = 1
	"let g:miniBufExplorerMoreThanOne = 1
	"let g:miniBufExplMapWindowNavVim = 1
	"let g:miniBufExplMapWindowNavArrows = 1
	"let g:miniBufExplMapCTabSwitchBufs = 1
	"let g:miniBufExplUseSingleClick = 1
	"let g:miniBufExplModSelTarget = 1
	"let g:miniBufExplForceSyntaxEnable = 1

	" ======================================================================
	" ## Open NerdTree
	" ====================================================================== "au VimEnter * NERDTree|wincmd p
	"au TabEnter * NERDTreeMirror|wincmd p
	map <leader>tf :NERDTreeToggle<CR>

	" ======================================================================
	" ## SuperTab - Allows us to get code completion with tab
	" ======================================================================
	"let g:SuperTabDefaultCompletiontype = "context"

	" ======================================================================
	" ## TagList
	" ======================================================================
	let Tlist_Show_One_File=1
	let Tlist_Exit_OnlyWindow=1
	map <leader>tl :TlistToggle<CR>

	" ======================================================================
	" ## TaskList
	" ======================================================================
	map <leader>ta <Plug>TaskList

" ======================================================================
" # EOF
" ======================================================================
