# Text cursor customization

cursor                  #c5c8c6
cursor_text_color       #1d1f21

# Scrollback

scrollbar_handle_color  foreground
scrollbar_track_color   #1d1f21

# Window layout

active_border_color     #5e8d87
inactive_border_color   #373b41
bell_border_color       #a54242

# Tab bar

active_tab_foreground   #e0e0e0
active_tab_background   #5e8d87
active_tab_font_style   bold
inactive_tab_foreground #c5c8c6
inactive_tab_background #373b41
inactive_tab_font_style normal

tab_bar_background      none
tab_bar_margin_color    none

# Color scheme

foreground              #c5c8c6
background              #1d1f21

selection_foreground    #e0e0e0
selection_background    #5294e2

# The color table

color0                  #282a2e
color8                  #969896

color1                  #a54242
color9                  #cc6666

color2                  #8c9440
color10                 #b5bd68

color3                  #de935f
color11                 #f0c674

color4                  #5f819d
color12                 #81a2be

color5                  #85678f
color13                 #b294bb

color6                  #5e8d87
color14                 #8abeb7

color7                  #c5c8c6
color15                 #ffffff
