#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Terminate ssh-agent daemon started by Prezto
ssh_auth_sock=${SSH_AUTH_SOCK:-$HOME/.cache/prezto/ssh-agent.sock}
if [[ $ssh_auth_sock == $HOME/**/prezto/ssh-agent.sock ]] &&
   [[ -S $ssh_auth_sock ]]
then
    kill $(grep -oP '(?<=SSH_AGENT_PID=)\d+' ${ssh_auth_sock/%sock/env})
fi
unset ssh_auth_sock

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "So long and thanks for all the fish.\n  -- Douglas Adams"
    "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  --Truman Burbank"
)

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
