#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

case "$OSTYPE" in
  darwin*)  export BROWSER='open' ;;
  linux*)   export BROWSER='xdg-open' ;;
esac

#
# Editors
#

export EDITOR='vim'
export VISUAL='emacs'
export PAGER='less'

#
# Terminal
#

# Set default terminal used by `i3-sensible-terminal` and `rofi-sensible-terminal`
export TERMINAL=kitty

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  $HOME/.local/bin
  # /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Personal
#

# Emacs variable `user-mail-address` defaults to this env
export EMAIL=cantoraz@gmail.com

#
# Secrets
#

if [[ -e $HOME/.secrets ]]; then
  source $HOME/.secrets
fi
