#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" ]]; then
    case "$OSTYPE" in
        darwin*)  export BROWSER='open' ;;
        linux*)   export BROWSER='xdg-open' ;;
    esac
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
    export EDITOR='nvim'
fi
if [[ -z "$VISUAL" ]]; then
    export VISUAL='emacs'
fi
if [[ -z "$PAGER" ]]; then
    export PAGER='less'
fi

#
# Terminal
#

# Set default terminal used by `i3-sensible-terminal` and `rofi-sensible-terminal`
export TERMINAL=kitty

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{s,}bin(N)
  $HOME/.local/{s,}bin(N)
  # /opt/{homebrew,local}/{,s}bin(N)
  # /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Set the type of specified Unicode characters that Less treats them as.
# Nerd Fonts defines icon characters in Private Use Area, in which range
# characters are normally treated as binary characters. Less should be
# telled to treat such characters as printable.
if [[ -z "$LESSUTFCHARDEF" ]]; then
  export LESSUTFCHARDEF=e000-f8ff:p,f0001-fffff:p
fi

#
# Personal
#

# Emacs variable `user-mail-address` defaults to this env
export EMAIL=cantoraz@gmail.com

#
# Secrets
#

if [[ -e $HOME/.secrets ]]; then
  source $HOME/.secrets
fi
