#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Cantroaz Chou <cantoraz@gmail.com>
#

# Source my customization before Prezto
# Usually they define environment variables on which some modules of Prezto might rely.
# Maybe the best position for them is `.zshenv'.
for config_file ($HOME/.zshrc.before.d/*.zsh(N)) source $config_file
unset config_file

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Source my customization
for config_file ($HOME/.zshrc.d/*.zsh(N)) source $config_file
unset config_file
