#
# Executes commands at the start of an interactive session.
#

# Source my customization before Prezto
# Usually they define environment variables on which some modules of Prezto might rely.
# Maybe the best position for them is `.zshenv'.
for config_file ($HOME/.zshrc.before.d/*.zsh(N)) source $config_file
unset config_file

# Source zshrc from Prezto
prezto_zshrc="${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
[[ -s $prezto_zshrc ]] && source $prezto_zshrc
unset prezto_zshrc

# Source my customization
for config_file ($HOME/.zshrc.d/*.zsh(N)) source $config_file
unset config_file

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
