# vim: ft=tmux

set -g  @bg             "#1d1f21"   # base00
set -g  @light-bg       "#282a2e"   # base01
set -g  @xlight-bg      "#373b41"   # base02
set -g  @xxlight-bg     "#969896"   # base03
set -g  @dark-fg        "#b4b7b4"   # base04
set -g  @fg             "#c5c8c6"   # base05
set -g  @light-fg       "#e0e0e0"   # base06
set -g  @xlight-fg      "#ffffff"   # base07

set -g  @cursor         "#c5c8c6"   # base05

set -g  @on-tint        "#e0e0e0"   # base06
set -g  @tint           "#5e8d87"   # color6

set -g  @black          "#282a2e"   # color0    base01
set -g  @bright-black   "#969896"   # color8    base03
set -g  @red            "#a54242"   # color1
set -g  @bright-red     "#cc6666"   # color9
set -g  @green          "#8c9440"   # color2
set -g  @bright-green   "#b5bd68"   # color10
set -g  @yellow         "#de935f"   # color3
set -g  @bright-yellow  "#f0c674"   # color11
set -g  @blue           "#5f819d"   # color4
set -g  @bright-blue    "#81a2be"   # color12
set -g  @magenta        "#85678f"   # color5
set -g  @bright-magenta "#b294bb"   # color13
set -g  @cyan           "#5e8d87"   # color6
set -g  @bright-cyan    "#8abeb7"   # color14
set -g  @white          "#c5c8c6"   # color7    base05
set -g  @bright-white   "#ffffff"   # color15   base07
